update

diff --git a/scripts/install_bin_external b/scripts/install_bin_external
--- a/scripts/install_bin_external
+++ b/scripts/install_bin_external
@@ -4,7 +4,7 @@ readonly cf="\\033[0m"
 readonly red="\\033[0;31m"
 
 readonly BIN_SCRIPTS="$BIN_SCRIPTS"
-BIN_SCRIPTS_EX=""
+BIN_SCRIPTS_BIN_EX=""
 
 log_err() {
   echo -e "${red}❌${cf} $1" 1>&2
@@ -45,44 +45,44 @@ is_c_file() {
 if [[ -z "$BIN_SCRIPTS" ]]; then
   err_exit "\$BIN_SCRIPTS is not found"
 else
-  BIN_SCRIPTS_EX="$BIN_SCRIPTS/bin/ex"
-  if [[ ! -d "$BIN_SCRIPTS_EX" ]]; then
-    mkdir -p "$BIN_SCRIPTS_EX"
+  BIN_SCRIPTS_BIN_EX="$BIN_SCRIPTS/bin/ex"
+  if [[ ! -d "$BIN_SCRIPTS_BIN_EX" ]]; then
+    mkdir -p "$BIN_SCRIPTS_BIN_EX"
     if is_err; then
-      err_exit "can't create directory \$BIN_SCRIPTS_EX"
+      err_exit "can't create directory \$BIN_SCRIPTS_BIN_EX"
     fi
   fi
 fi
 
 install_tfref() {
-  curl -s https://raw.githubusercontent.com/kis9a/tfref/main/tfref >"$BIN_SCRIPTS_EX/tfref"
-  chmod +x "$BIN_SCRIPTS_EX/tfref"
+  curl -s https://raw.githubusercontent.com/kis9a/tfref/main/tfref >"$BIN_SCRIPTS_BIN_EX/tfref"
+  chmod +x "$BIN_SCRIPTS_BIN_EX/tfref"
 }
 
 install_runeboxes() {
-  curl -s https://raw.githubusercontent.com/kis9a/runeboxes/main/runeboxes >"$BIN_SCRIPTS_EX/runeboxes"
-  chmod +x "$BIN_SCRIPTS_EX/runeboxes"
+  curl -s https://raw.githubusercontent.com/kis9a/runeboxes/main/runeboxes >"$BIN_SCRIPTS_BIN_EX/runeboxes"
+  chmod +x "$BIN_SCRIPTS_BIN_EX/runeboxes"
 }
 
 install_runeflex() {
-  curl -s https://raw.githubusercontent.com/kis9a/runeflex/main/runeflex >"$BIN_SCRIPTS_EX/runeflex"
-  chmod +x "$BIN_SCRIPTS_EX/runeflex"
+  curl -s https://raw.githubusercontent.com/kis9a/runeflex/main/runeflex >"$BIN_SCRIPTS_BIN_EX/runeflex"
+  chmod +x "$BIN_SCRIPTS_BIN_EX/runeflex"
 }
 
 install_runeflexrn() {
-  curl -s https://raw.githubusercontent.com/kis9a/runeflex/main/runeflexrn >"$BIN_SCRIPTS_EX/runeflexrn"
-  chmod +x "$BIN_SCRIPTS_EX/runeflexrn"
+  curl -s https://raw.githubusercontent.com/kis9a/runeflex/main/runeflexrn >"$BIN_SCRIPTS_BIN_EX/runeflexrn"
+  chmod +x "$BIN_SCRIPTS_BIN_EX/runeflexrn"
 }
 
-install_c_files() {
+install_c99_scripts() {
   local ls
   if ! is_exists_command "c99"; then
     return 1
   else
-    ls=$(ls "$BIN_SCRIPTS/bin")
+    ls=$(ls "$BIN_SCRIPTS/src/c99/scripts")
     while read -r f; do
       if is_c_file "$f"; then
-        c99 "$BIN_SCRIPTS/bin/$f" -o "$BIN_SCRIPTS_EX/${f%.c}"
+        c99 "$BIN_SCRIPTS/src/c99/scripts/$f" -o "$BIN_SCRIPTS_BIN_EX/${f%.c}"
       fi
     done <<<"$ls"
   fi
@@ -104,6 +104,6 @@ if ! is_exists_command "runeflexrn"; then
   install_runeflexrn
 fi
 
-if ! install_c_files; then
-  log_err "failed install c files"
+if ! install_c99_scripts; then
+  log_err "failed install c99 scripts"
 fi
